server:
  port: 8090
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: off
  jmx:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: socnet
    password: socnet
    url: jdbc:postgresql://localhost:5432/socnetdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0.1_000
    url: ${spring.datasource.url}
    user: socnet
    password: socnet

